### ISSUE TITLE
publish 2.2.2

### ISSUE THREAD

**Issue by antonkulaga** [jodersky/flow#15]
What I get when I try to resolve it
```
[warn]     ::::::::::::::::::::::::::::::::::::::::::::::
[warn]     ::          UNRESOLVED DEPENDENCIES         ::
[warn]     ::::::::::::::::::::::::::::::::::::::::::::::
[warn]     :: com.github.jodersky#flow_2.11;2.2.2: not found
[warn]     ::::::::::::::::::::::::::::::::::::::::::::::
```

**Comment by jodersky** [comment]
Flow is published to bintray, repo `jodersky/flow`. Nevertheless, it is linked to JCenter, a repository that is included by default in the sbt resolvers (for sbt 0.13.6+).

Should there still be resolver issues, starting from version 2.2.4, flow is synced with maven central, making it once again available on maven central.
