### ISSUE TITLE
Error while building

### ISSUE THREAD

**Issue by joesan** [jodersky/flow#16]
I'm trying to follow through the documentation to build the project and I git the following error. I'm at the top folder when I issued the sbt command. Here is the error that I get!

My-MacBook-Pro:flow joe$ sbt flow/packageBin
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=724M; support was removed in 8.0
[info] Loading project definition from /Projects/flow/project
[info] Set current project to root (in build file:/Projects/flow/)
[error] Expected ID character
[error] Not a valid command: flow (similar: loadp)
[error] Expected project ID
[error] Expected configuration
[error] Expected ':' (if selecting a configuration)
[error] Expected key
[error] Not a valid key: flow (similar: fork)
[error] flow/packageBin
[error]     ^
My-MacBook-Pro:flow joe$ 

Any clues?

**Comment by jodersky** [comment]
The project names in the documentation are out of date, sorry, I'll fix that. Run `sbt flow-main/packageBin` instead.

By the way, should you get other errors containing `Expected project ID`, you can always run `sbt` to get an interactive shell and then list all projects by entering `projects`
