### ISSUE TITLE
Issue when Building Native library on Mac OS X with JDK 1.8

### ISSUE THREAD

**Issue by joesan** [jodersky/flow#17]
When trying to do a 

sh ./bootstrap

I get the following error:

./bootstrap: line 3: autoreconf: command not found

**Comment by jodersky** [comment]
You are probably missing required tools. To bootstrap the native build you
need:

- autoconf
- automake
- libtool

Then, to actually compile, you need (this will be checked by `./configure`):

- an installed JDK (preferebly, also set the environment variable JAVA_HOME
in case jni headers are not found)
- a c compiler

These dependencies should definitely be in the documentation, I'll add them
asap

**Comment by jodersky** [comment]
In case you're on a Debian-based OS such as Ubuntu, the required dependencies can be installed with

`sudo apt-get install build-essential autoconf automake libtool`

I assume you already have a JDK, otherwise `sudo apt-get install openjdk-8-jdk`

**Comment by jodersky** [comment]
Updated documentation

**Comment by joesan** [comment]
I used the following gist to install the missing tools on my Mac:

https://gist.github.com/jellybeansoup/4192307

I'm running into the following error now:

autoreconf: Entering directory `.'
autoreconf: configure.ac: not using Gettext
autoreconf: running: aclocal -I m4 --output=aclocal.m4t
Can't exec "aclocal": No such file or directory at /usr/local/share/autoconf/Autom4te/FileUtils.pm line 326.
autoreconf: failed to run aclocal: No such file or directory

**Comment by joesan** [comment]
After tinkering with the version of the autoconf installation, I managed to get until this point:

autoreconf: Entering directory `.'
autoreconf: configure.ac: not using Gettext
autoreconf: running: aclocal --force -I m4
main::scan_file() called too early to check prototype at /usr/local/bin/aclocal line 617.
autoreconf: configure.ac: tracing
autoreconf: configure.ac: not using Libtool
autoreconf: running: /usr/local/bin/autoconf --force
autoreconf: running: /usr/local/bin/autoheader --force
autoreconf: running: automake --add-missing --copy --force-missing
Useless use of /d modifier in transliteration operator at /usr/local/share/automake-1.11/Automake/Wrap.pm line 58.
configure.ac:9: installing `./install-sh'
configure.ac:9: installing `./missing'
src/Makefile.am:1: Libtool library used but `LIBTOOL' is undefined
src/Makefile.am:1:   The usual way to define `LIBTOOL' is to add `AC_PROG_LIBTOOL'
src/Makefile.am:1:   to `configure.ac' and run `aclocal' and `autoconf' again.
src/Makefile.am:1:   If `AC_PROG_LIBTOOL' is in `configure.ac', make sure
src/Makefile.am:1:   its definition is in aclocal's search path.
src/Makefile.am: installing `./depcomp'
autoreconf: automake failed with exit status: 1

**Comment by joesan** [comment]
I'm on a Mac. Does that help?

**Comment by jodersky** [comment]
I've successfully tested it in the past on a mac. It looks like there is some kind of incompatibility with the `configure.ac` file and your version of autoconf.

I'm currently looking into details

**Comment by joesan** [comment]
I'm now fiddling around getting a C compiler installed on m Mac!

Thanks for the support!

**Comment by jodersky** [comment]
If I recall correctly, you can get GCC through XCode. However I also heard that Mac now supports CLang.

**Comment by jodersky** [comment]
Regarding the issue, do you have any autoconf scripts (*.ac) or the autotools sources you downloaded in flow's root directory?
Also did you run the download script in `flow-native`?
Having unrelated ac scripts in the current or parent directory is apparently known to cause issues.

**Comment by jodersky** [comment]
I noticed the script you used doesn't download the latest versions. Try uninstalling your current autotools and rerun the script, substituting with the following urls:

http://ftpmirror.gnu.org/autoconf/autoconf-2.69.tar.gz
http://ftpmirror.gnu.org/automake/automake-1.15.tar.gz
http://ftpmirror.gnu.org/libtool/libtool-2.4.2.tar.gz

**Comment by jodersky** [comment]
I just made a source release, available https://bintray.com/artifact/download/jodersky/generic/flow-native-srcrelease.tar.gz

This is a clean git checkout but I already ran `./bootstrap` on it. It can be compiled with `./configure && make`

**Comment by joesan** [comment]
I will give that a try and let you know how it went!

**Comment by joesan** [comment]
Here is the next hurdle:

checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... ./install-sh -c -d
checking for gawk... no
checking for mawk... no
checking for nawk... no
checking for awk... awk
checking whether make sets $(MAKE)... no
checking whether make supports nested variables... no
checking for gcc... gcc
checking whether the C compiler works... no
configure: error: in `/Users/joe/Downloads/flow-native-srcrelease':
configure: error: C compiler cannot create executables
See `config.log' for more details

The config.log shows the following... Looks like I need gcc > version 5?

configure:2956: found /usr/local/bin/gcc
configure:2967: result: gcc
configure:3196: checking for C compiler version
configure:3205: gcc --version >&5
gcc (GCC) 4.9.2 20141029 (prerelease)
Copyright (C) 2014 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

**Comment by joesan** [comment]
I had to do the following to get the flow-native-srcrelase to be compiled:

1. install C
2. add it to the PATH

https://wiki.helsinki.fi/display/HUGG/Installing+the+GNU+compilers+on+Mac+OS+X

After this, I had to try out compiling a small C program which showed me the licence details of XCode that I had to agree to.

**Comment by joesan** [comment]
Even this would not work:

./configure && make -I/Library/Java/JavaVirtualMachines/jdk1.8.0_60.jdk/Contents/Home/include

But there is the jni.h file located in the Library path!

**Comment by jodersky** [comment]
>  Looks like I need gcc > version 5?

Not strictly required in an unbootstrapped release. However, the link I sent you is a bootstrapped source release from my system, which uses GCC 5.2.1.


> After this, I had to try out compiling a small C program which showed me the licence details of XCode that I had to agree to. 

Wow. XCode makes installing GCC way over-complicated!


> So now, this is the next hurdle that I hit: [missing JNI headers]

When I set up `configure.ac`, the java-header-search-script that I used contained this: `/System/Library/Frameworks/JavaVM.framework/Versions/Current/Headers/jni.h`, which I reckon was the default Java installation path on Mac OS X. This has apparently changed, which version of OS X are you using?

A quick fix to this is setting the JAVA_HOME environment variable before running `./configure`.
```
export JAVA_HOME=<path to jvm installation directory>
./configure && make
```

**Comment by joesan** [comment]
I do have JAVA_HOME set in my .bash_profile. I will try doing it explicitly again and run the make script and post the results! Thanks for your support!

**Comment by jodersky** [comment]
Does your JAVA_HOME point to the right location? Do you have a JDK (Java Development Kit) installed, not just the JRE (Ja Runtime Environment)? This is required as the latter does not include jni headers.

By the way, I just read about "macports" and "homebrew", package managers for OS X. Using a package manager makes things A LOT simpler (I use `apt` on Debian).

Installing autotools then becomes as simple as `sudo port install automake autoconf libtool

**Comment by joesan** [comment]
Yes, I have a complete JDK installation. Here is what I have on my .bash_profile!

export JAVA_HOME_8=$(/usr/libexec/java_home -v 1.8.0_60)

**Comment by jodersky** [comment]
What does `/usr/libexec/java_home -v 1.8.0_60` evaulate to?

**Comment by joesan** [comment]
Sorry for the late reply! Was stuck with some other tasks at work. 

So the /usr/libexec/java_home -v 1.8.0_60 points to /Library/Java/JavaVirtualMachines/jdk1.8.0_60.jdk/Contents/Home

**Comment by joesan** [comment]
I now did the following:

export JAVA_HOME=/Library/Java/JavaVirtualMachines/jdk1.8.0_60.jdk/Contents/Home/include/

and then ran the ./configure && make which gave me the following error:

Making all in src
/bin/sh ../libtool  --tag=CC   --mode=compile gcc -DHAVE_CONFIG_H -I. -I..   -I/Library/Java/JavaVirtualMachines/jdk1.8.0_60.jdk/Contents/Home/include  -g -O2 -MT flow_jni.lo -MD -MP -MF .deps/flow_jni.Tpo -c -o flow_jni.lo flow_jni.c
libtool: compile:  gcc -DHAVE_CONFIG_H -I. -I.. -I/Library/Java/JavaVirtualMachines/jdk1.8.0_60.jdk/Contents/Home/include -g -O2 -MT flow_jni.lo -MD -MP -MF .deps/flow_jni.Tpo -c flow_jni.c  -fno-common -DPIC -o .libs/flow_jni.o
In file included from com_github_jodersky_flow_internal_NativeSerial.h:2:0,
                 from flow_jni.c:2:
/Library/Java/JavaVirtualMachines/jdk1.8.0_60.jdk/Contents/Home/include/jni.h:45:20: fatal error: jni_md.h: No such file or directory
 #include "jni_md.h"
                    ^
compilation terminated.
make[2]: *** [flow_jni.lo] Error 1
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2

**Comment by jodersky** [comment]
Making progress :)

Try the same with `export JAVA_HOME=/Library/Java/JavaVirtualMachines/jdk1.8.0_60.jdk/Contents/Home/`, or equivalently `export JAVA_HOME=$(/usr/libexec/java_home -v 1.8.0_60)` (similar to what you have in your .bas_profile but without the _8 appended to JAVA_HOME)

I managed to get access to a Mac, I'll also retry the compilation process on my side. Just so I can compare my results, what OS X version are you using?

**Comment by joesan** [comment]
I'm using Yosemite 10.10.4!

It would be great if you could try it with your Mac and share your experience!

**Comment by jodersky** [comment]
Here is what I did on Mac OS X Mountain Lion (10.8), the process should be essentially the same on Yosemite, however.

1. Install MacPorts, as described on their website https://www.macports.org/install.php
2. Install autotools: `sudo port install automake autoconf libtool`
3. Install OpenJDK 8, as described here http://www.oracle.com/technetwork/java/javase/downloads/jdk8-downloads-2133151.html
4. Clone flow `git clone https://github.com/jodersky/flow flow`
5. `cd flow flow/flow-native`
6. `./bootstrap`
7. `./configure && make`
8. All done with no problems encountered.

The problem you are currently experiencing "jni_md.h: No such file or directory" is related to `./configure` not including the directory where "jni_md.h" is located. Could you please tell me where this file is located in Yosemite? It should be somewhere inside `JAVA_HOME`.
Also, did setting `JAVA_HOME=$(/usr/libexec/java_home -v 1.8.0_60)`, as I described in my previous post, solve any problems?

**Comment by joesan** [comment]
No! Setting JAVA_HOME=$(/usr/libexec/java_home -v 1.8.0_60) did not help either!

Could you please tell me where is your jni_md.h located?

**Comment by jodersky** [comment]
Ok I just figured what's going on. On my Mac I had an old version of JDK 1.6 installed which `./configure` was using. It seems that the new JDK 1.8 uses a different internal file structure (actually it looks like it uses the same as on Linux now), thus thwarting autotools.
I'll see how to correct `configure.ac` to detect the new layout.

**Comment by joesan** [comment]
I will give it a try with Java 1.6 to see if it works!

**Comment by jodersky** [comment]
Sure, but I consider it a bug if it doesn't work with Java 1.8; especially since the upcoming Akka 2.4 will require java 1.8.
I'm looking into a fix.

**Comment by joesan** [comment]
No I did not have Java 6. I tried with Java 7 and it still is the same problem!

**Comment by joesan** [comment]
My plan is to use your library to connect my Arduino controller to the RasPi where this library would be running to get messages from my Arduino. If I could get this library up and running into my Play WebApp on the RasPi, that would be great!

**Comment by jodersky** [comment]
Well, if it should run on the raspberry pi, you can compile the native part of flow on it anyway. Assuming you are on raspbian (or any other Debian-based distro), this should be pretty simple:

1. `sudo apt-get install build-essential autoconf automake libtool openjdk-X-jdk` (where X is the version you'd like 7 or 8)
2. `git clone https://github.com/jodersky/flow flow`
3. `cd flow/flow-native`
4. `./bootstrap`
5. `./configure && make`
6. Refer to documentation on how to install the library

I hope that helps you get started on the Pi, nevertheless I still want to fix the JDK 8 on OSX issue.

**Comment by jodersky** [comment]
I just checked out the file structure of JDK 1.7 and it also follows that of 1.8. So it seems that Apple had a special organisation up to JDK 1.6.

Since java 1.6 is quite old now and since the next minor release of Akka will require java 1.8, I reckon the most reasonable thing to do is fix the `configure.ac` and require a minimum of java 1.7 on Mac OS X to build the native part.

**Comment by joesan** [comment]
I will give the steps you mentioned on a RasPi and post the results!

**Comment by jodersky** [comment]
I tested a potential fix, everything should be good now.
