### ISSUE TITLE
any guidance how to make it work for windows?

### ISSUE THREAD

**Issue by antonkulaga** [jodersky/flow#20]
A friend of mine has to demostrate spectophotometer gui for windows but I am not sure what exactly I should do to make it work for windows. I can try to install windows32 to VM and try to build native libs inside VM but it will be very time consuming for me. Maybe you already have prebuild binaries for windows 32 and windows 64 to download/install?

**Comment by jodersky** [comment]
Unfortunately windows' "low-level" API is very different to Linux/Mac (so called POSIX). This makes it impossible to simply compile the existing source for Windows. Nevertheless, there are ways in which you should be able to get flow to work on windows, they however aren't "easy fixes" and require considerable time and skills in C development.

Here are two ways that I can think of:

1. Port the native part of flow to windows. There is already a file `flow-native/src/platform/windows/flow.c.disabled` that contains *interesting* code for windows that uses serial ports. It is however only potential resource, not a draft or working implementation.

2. Compile the existing library on Cygwin (Cygwin is basically POSIX for windows). This might even work out of the box!

Should you decide to build for windows please share your results, having flow on windows would be a very useful feature!

**Comment by jodersky** [comment]
Answering you got me intrigued with the cygwin way. I *might* have a solution coming really soon.

**Comment by xl0** [comment]
Hey,

tried with cygwin on 32-bit XP (in kvm). Seems to build fine, just had to pass LDFLAGS=-no-undefined to make. Anton should be able to test tomorrow (as I'm completely clueless about java).

**Comment by jodersky** [comment]
Cool! I just tried on windows 7 64 bit with cygwin, it also works fine just
needed to add another flag "-D __int64=int64_t" to the compiler.

Now I'll update autotools to add said settings and bundle cygwin dll with
the fat jar. A windows version should be ready soon

**Comment by jodersky** [comment]
A quick update
I managed to get everything compiled under cygwin and was able to load `cygwin1.dll` and the resulting `cygflow.dll` native libraries from the jvm. However I did not have a serial device close to test when I implemented the cygwin support.

Also, the current status is pretty dirty, the native loader and library initialization code has to be fixed.
All work is available under the `wip-cygwin` branch. I won't have much time in the next days to get this implemented properly. Any help is welcome.

**Comment by antonkulaga** [comment]
Any progress on this issue?

**Comment by jodersky** [comment]
Hey, the progress is still as it stands on the previous message. Personally, I don't have windows and I will not have time to look into it in the foreseeable future.
Anyone is welcome to take on the issue though.

**Comment by antonkulaga** [comment]
@jodersky actually @xl0  needs a lot, but @xl0 is mostly C++ developer so he does not understand Scala (I can help a bit but the problem is I do not have free time and I do not understand how you work with native libs). If @xl0 will manage to compile native part for windows, will you put it to the default list of native libs?

**Comment by jodersky** [comment]
> @xl0 is mostly C++ developer so he does not understand Scala

That's no problem at all, in fact knowing C or C++ is very useful for implementing a new backend for windows.
Also, you shouldn't need to change any scala code. The interface between the jvm and native code happens in the following two files:
[NativeSerial.java](https://github.com/jodersky/flow/blob/master/flow-main/src/main/java/com/github/jodersky/flow/internal/NativeSerial.java) and [NativeSerial.h](https://github.com/jodersky/flow/blob/master/flow-native/src/com_github_jodersky_flow_internal_NativeSerial.h)

To implement a new backend, essentially all that is required is to implement the functions defined in [flow.h](https://github.com/jodersky/flow/blob/master/flow-native/src/flow.h)

> If @xl0 will manage to compile native part for windows, will you put it to the default list of native libs?

yes, that would be awesome!

**Comment by xl0** [comment]
Hey,

unfortunately I won't have time to port the backend natively. It compiles with cygwin, and for us, this would be a viable solution.

**Comment by jodersky** [comment]
It compiles under cygwin so in theory it should work, however you will have
to launch flow through cygwin as well.

I can include a native binary for cygwin in an experimental release, if you
can confirm that it works I'll ship it in the main native jar

**Comment by rjumko** [comment]
Hello. How can I get experimental release with native binary for cygwin?

**Comment by jodersky** [comment]
I never made one that worked. In flow 2.4 the library loading mechanism will be changed, making it possible to support a wider range of systems, including potentially windows.

What version of windows do you have? I can build something under Cygwin, windows 10, no guarantee about backwards-compatibility though

**Comment by rjumko** [comment]
I have 64 and 32-bit windows 10. And can check for both systems.

**Comment by dsutic** [comment]
+1 for windows version, I can check for windows 8.1

**Comment by jodersky** [comment]
Closing this as the build system has changed and no considerable progress has yet been made on the issue. Please see #32 for follow-up.
