### ISSUE TITLE
Unable to use Flow 2.4.0-M2 (unreleased dependency?)

### ISSUE THREAD

**Issue by mthmulders** [jodersky/flow#24]
It seems I'm unable to use Flow 2.4.0-M2 in my SBT-based project. When I try `sbt assembly`, I get:

    [warn] 	module not found: ch.jodersky#jni-library_2.11;0.2-SNAPSHOT
    [warn] ==== local: tried
    [warn]   /Users/maarten/.ivy2/local/ch.jodersky/jni-library_2.11/0.2-SNAPSHOT/ivys/ivy.xml
    [warn] ==== jcenter: tried
    [warn]   https://jcenter.bintray.com/ch/jodersky/jni-library_2.11/0.2-SNAPSHOT/jni-library_2.11-0.2-SNAPSHOT.pom
    [warn] ==== public: tried
    [warn]   https://repo1.maven.org/maven2/ch/jodersky/jni-library_2.11/0.2-SNAPSHOT/jni-library_2.11-0.2-SNAPSHOT.pom
    [info] Resolving jline#jline;2.12.1 ...
    [warn] 	::::::::::::::::::::::::::::::::::::::::::::::
    [warn] 	::          UNRESOLVED DEPENDENCIES         ::
    [warn] 	::::::::::::::::::::::::::::::::::::::::::::::
    [warn] 	:: ch.jodersky#jni-library_2.11;0.2-SNAPSHOT: not found
    [warn] 	::::::::::::::::::::::::::::::::::::::::::::::
    [warn] 
    [warn] 	Note: Unresolved dependencies path:
    [warn] 		ch.jodersky:jni-library_2.11:0.2-SNAPSHOT
    [warn] 		  +- com.github.jodersky:flow_2.11:2.4.0-M2 (/Users/maarten/Projects/hyperion/build.sbt#L59)
    [warn] 		  +- hyperion:hyperion-meter-agent_2.11:1.0.0-SNAPSHOT

My first guess that it's due to using a non-released version of jni-library...

**Comment by jodersky** [comment]
You're right, sorry. I'm in the processing of updating sbt-jni as well, in the mean-time you can work around the problem by checking out jodersky/sbt-jni@c85463d30f73a43eb5275c504657a5117c126ca4 and running `sbt publishLocal` to publish the 0.2-SNAPSHOT release locally

**Comment by jodersky** [comment]
It should be fixed in the 2.4.0 release

**Comment by mthmulders** [comment]
Works like a charm, thanks!
