### ISSUE TITLE
latest versions not in maven central ?

### ISSUE THREAD

**Issue by gbrd** [jodersky/flow#25]
hum, I can not find last version in maven central, in which repository is it available ?

http://search.maven.org/#search%7Cga%7C1%7Cg%3A%22com.github.jodersky%22%20

**Comment by jodersky** [comment]
Thanks for submitting the issue. The latest version (2.5) renamed the main project and I forgot to include it in the repository.

Currently all packages are available in my personal [bintray repository](https://bintray.com/jodersky/maven). However, I also just submitted a request to have them included in jcenter so you can expect them to be available there in a couple of business days.

What build tool do you use? In case of gradle or sbt, jcenter is resolved out-of-the box. In maven you'll have to add http://jcenter.bintray.com/ to the respositories.

**Comment by jodersky** [comment]
All packages are now available in [Bintray jcenter](http://jcenter.bintray.com/com/github/jodersky/).
