### ISSUE TITLE
Watching Events on Port

### ISSUE THREAD

**Issue by jishnair** [jodersky/flow#40]
How can I implement a "Watch" for specific events on a port? For example I want to get a message if the CTS line has changed state.

**Comment by jodersky** [comment]
"Watch" events work on the file descriptor level, that is they only provide information on when a device is connected or disconnected (it's up to the OS to determine what that means).

On a general note, the library currently only supports RxTx data transfers. Access to control wires is not supported.

**Comment by jishnair** [comment]
OK. Thank you !
